id: A84BC9FF7
title: 'The Honey of Devotion: A Prayer to the Garland of Glorious Karmapa Incarnations'
type: translation
pechas:
- I118238CC
- I3AAA3D95
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:47.675376
  last_modified_at: 2023-01-04 11:51:47.675391
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I118238CC/4E8F: F498
  I3AAA3D95/0B24: F498
